### PR TITLE
create-td-uki : fix permission denied issue

### LINKED ISSUE #352: Permission issue with create-td-uki script
**Describe the bug**
In short, executing `./create-td-uki.sh tdx-guest-ubuntu-24.04-generic.qcow2` leads to `virt-customize: error: libguestfs error: /usr/bin/supermin exited with error status 1`

After ` export LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1`, the output says:
```
cleanup ...
Formatting '/home/***/guest-tools/image/tdx-guest-tmp.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=57445187584 backing_file=tdx-guest-ubuntu-24.04-generic.qcow2 backing_fmt=qcow2 lazy_refcounts=off refcount_bits=16
[   0.0] Examining the guest ...
libguestfs: trace: set_verbose true
libguestfs: trace: set_verbose = 0
libguestfs: trace: set_network true
libguestfs: trace: set_network = 0
libguestfs: trace: add_drive "/home/***/guest-tools/image/tdx-guest-tmp.qcow2" "readonly:false" "protocol:file" "discard:besteffort"
libguestfs: trace: add_drive = 0
libguestfs: trace: launch
libguestfs: trace: max_disks
libguestfs: trace: max_disks = 255
libguestfs: trace: get_tmpdir
libguestfs: trace: get_tmpdir = "/tmp"
libguestfs: trace: version
libguestfs: trace: version = <struct guestfs_version = major: 1, minor: 52, release: 0, extra: , >
libguestfs: trace: get_backend
libguestfs: trace: get_backend = "direct"
libguestfs: launch: program=virt-customize
libguestfs: launch: version=1.52.0
libguestfs: launch: backend registered: libvirt
libguestfs: launch: backend registered: direct
libguestfs: launch: backend=direct
libguestfs: launch: tmpdir=/tmp/libguestfsUjE7A8
libguestfs: launch: umask=0002
libguestfs: launch: euid=1000
libguestfs: trace: get_cachedir
libguestfs: trace: get_cachedir = "/var/tmp"
libguestfs: begin building supermin appliance
libguestfs: run supermin
libguestfs: command: run: /usr/bin/supermin
libguestfs: command: run: \ --build
libguestfs: command: run: \ --verbose
libguestfs: command: run: \ --if-newer
libguestfs: command: run: \ --lock /var/tmp/.guestfs-1000/lock
libguestfs: command: run: \ --copy-kernel
libguestfs: command: run: \ -f ext2
libguestfs: command: run: \ --host-cpu x86_64
libguestfs: command: run: \ /usr/lib/x86_64-linux-gnu/guestfs/supermin.d
libguestfs: command: run: \ -o /var/tmp/.guestfs-1000/appliance.d
supermin: version: 5.2.2
supermin: package handler: debian/dpkg
supermin: acquiring lock on /var/tmp/.guestfs-1000/lock
supermin: build: /usr/lib/x86_64-linux-gnu/guestfs/supermin.d
supermin: reading the supermin appliance
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/base.tar.gz type gzip base image (tar)
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/daemon.tar.gz type gzip base image (tar)
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/excludefiles type uncompressed excludefiles
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/hostfiles type uncompressed hostfiles
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/init.tar.gz type gzip base image (tar)
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/packages type uncompressed packages
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/packages-hfsplus type uncompressed packages
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/packages-reiserfs type uncompressed packages
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/packages-xfs type uncompressed packages
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/udev-rules.tar.gz type gzip base image (tar)
supermin: mapping package names to installed packages
supermin: resolving full list of package dependencies
supermin: build: 206 packages, including dependencies
supermin: build: 7935 files
supermin: build: 4251 files, after matching excludefiles
supermin: build: 4260 files, after adding hostfiles
supermin: build: 4260 files, after removing unreadable files
supermin: build: 4267 files, after munging
supermin: kernel: looking for kernel using environment variables ...
supermin: kernel: looking for kernels in /lib/modules/*/vmlinuz ...
supermin: kernel: looking for kernels in /boot ...
supermin: kernel: kernel version of /boot/vmlinuz-6.8.0-1022-intel = 6.8.0-1022-intel (from filename)
supermin: kernel: picked modules path /lib/modules/6.8.0-1022-intel
supermin: kernel: kernel version of /boot/vmlinuz-6.8.0-57-generic = 6.8.0-57-generic (from filename)
supermin: kernel: picked modules path /lib/modules/6.8.0-57-generic
supermin: kernel: picked vmlinuz /boot/vmlinuz-6.8.0-1022-intel
supermin: kernel: kernel_version 6.8.0-1022-intel
supermin: kernel: modpath /lib/modules/6.8.0-1022-intel
cp: cannot open '/boot/vmlinuz-6.8.0-1022-intel' for reading: Permission denied
supermin: cp -p '/boot/vmlinuz-6.8.0-1022-intel' '/var/tmp/.guestfs-1000/appliance.d.z4e6t4uq/kernel': command failed, see earlier errors
libguestfs: trace: launch = -1 (error)
virt-customize: error: libguestfs error: /usr/bin/supermin exited with
error status 1, see debug messages above

If reporting bugs, run virt-customize with debugging enabled and include
the complete output:

  virt-customize -v -x [...]
libguestfs: trace: close
libguestfs: closing guestfs handle 0x6146e4f5a250 (state 0)
libguestfs: command: run: rm
libguestfs: command: run: \ -rf /tmp/libguestfsUjE7A8
cleanup ...
```

**To Reproduce**
```
sudo ./create-td-image.sh -v 24.04
export LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1
./create-td-uki.sh tdx-guest-ubuntu-24.04-generic.qcow2
```

I also tried the following, but with the same result:
```
sudo ./create-td-image.sh -v 24.04
sudo chown <user>:<group> tdx-guest-ubuntu-24.04-generic.qcow2
export LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1
./create-td-uki.sh tdx-guest-ubuntu-24.04-generic.qcow2
```

**Expected behavior**
The script is supposed to create three files:
- the kernel of the guest image
- the initrd of the guest image
- the Unified Kernel Image that bundles together the kernel, the kernel's commandline and the initrd

**System report**
### Git ref

```
93fe38fa80f9754ae651adf57a0030fb64331906
```

### Operating system details

```
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.2 LTS
Release:        24.04
Codename:       noble
```

### Kernel version

```
6.8.0-1022-intel #29-Ubuntu SMP PREEMPT_DYNAMIC Wed Mar 12 16:31:57 UTC 2025 x86_64 x86_64 GNU/Linux
```

### TDX kernel logs

```
[    5.498049] virt/tdx: BIOS enabled: private KeyID range [64, 128)
[    5.498053] virt/tdx: Disable ACPI S3. Turn off TDX in the BIOS to use ACPI S3.
[   16.788469] virt/tdx: TDX module: attributes 0x0, vendor_id 0x8086, major_version 1, minor_version 5, build_date 20240129, build_num 698
[   16.788475] virt/tdx: CMR: [0x100000, 0x77800000)
[   16.788478] virt/tdx: CMR: [0x100000000, 0x407a000000)
[   16.788479] virt/tdx: CMR: [0x4080000000, 0x807c000000)
[   16.788480] virt/tdx: CMR: [0x8080000000, 0xc07c000000)
[   16.788482] virt/tdx: CMR: [0xc080000000, 0x1007c000000)
[   21.399079] virt/tdx: 4202516 KB allocated for PAMT
[   21.399091] virt/tdx: module initialized
...
[    5.498049] virt/tdx: BIOS enabled: private KeyID range [64, 128)
[    5.498053] virt/tdx: Disable ACPI S3. Turn off TDX in the BIOS to use ACPI S3.
[   16.788469] virt/tdx: TDX module: attributes 0x0, vendor_id 0x8086, major_version 1, minor_version 5, build_date 20240129, build_num 698
[   16.788475] virt/tdx: CMR: [0x100000, 0x77800000)
[   16.788478] virt/tdx: CMR: [0x100000000, 0x407a000000)
[   16.788479] virt/tdx: CMR: [0x4080000000, 0x807c000000)
[   16.788480] virt/tdx: CMR: [0x8080000000, 0xc07c000000)
[   16.788482] virt/tdx: CMR: [0xc080000000, 0x1007c000000)
[   21.399079] virt/tdx: 4202516 KB allocated for PAMT
[   21.399091] virt/tdx: module initialized
```

### TDX CPU instruction support

```
CPU supports TDX according to /proc/cpuinfo
```

### Model specific registers (MSRs)

```
MK_TME_ENABLED bit: 1 (expected value: 1)
SEAM_RR bit: 1 (expected value: 1)
NUM_TDX_PRIV_KEYS: 40
SGX_AND_MCHECK_STATUS: 0 (expected value: 0)
Production platform: Production (expected value: Production)
```

### CPU details

```
 INTEL(R) XEON(R) PLATINUM 8570
```

### QEMU package details

```
Status: Installed
Package: qemu-system-x86
Version: 2:8.2.2+ds-0ubuntu1.4+tdx1.1
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-release/ubuntu noble/main amd64 Packages
```

### Libvirt package details

```
Status: Installed
Package: libvirt-clients
Version: 10.0.0-2ubuntu8.3+tdx1.2
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-release/ubuntu noble/main amd64 Packages
```

### OVMF package details

```
Status: Installed
Package: ovmf
Version: 2024.02-3+tdx1.0
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-release/ubuntu noble/main amd64 Packages
```

### sgx-dcap-pccs package details

```
Status: Installed
Package: sgx-dcap-pccs
Version: 1.21-0ubuntu1
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-attestation-release/ubuntu noble/main amd64 Packages
```

### tdx-qgs package details

```
Status: Installed
Package: tdx-qgs
Version: 1.21-0ubuntu2.2
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-attestation-release/ubuntu noble/main amd64 Packages
```

### sgx-ra-service package details

```
Status: Installed
Package: sgx-ra-service
Version: 1.21-0ubuntu2.2
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-attestation-release/ubuntu noble/main amd64 Packages
Description: Intel(R) Software Guard Extensions Multi-Package Registration Agent Service
```

### sgx-pck-id-retrieval-tool package details

```
Status: Installed
Package: sgx-pck-id-retrieval-tool
Version: 1.21-0ubuntu2.2
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-attestation-release/ubuntu noble/main amd64 Packages
```

### QGSD service status

```
● qgsd.service - Intel(R) TD Quoting Generation Service
     Loaded: loaded (/usr/lib/systemd/system/qgsd.service; enabled; preset: enabled)
     Active: active (running) since Thu 2025-04-10 04:32:26 PDT; 1 week 6 days ago
    Process: 3320 ExecStartPre=/bin/chown -R qgsd:qgsd /var/opt/qgsd/ (code=exited, status=0/SUCCESS)
    Process: 3362 ExecStartPre=/bin/chmod 0750 /var/opt/qgsd/ (code=exited, status=0/SUCCESS)
    Process: 3380 ExecStartPre=/usr/share/qgs/linksgx.sh (code=exited, status=0/SUCCESS)
    Process: 3416 ExecStart=/usr/bin/qgs (code=exited, status=0/SUCCESS)
   Main PID: 3420 (qgs)
      Tasks: 5 (limit: 629145)
     Memory: 12.0M (peak: 13.0M)
        CPU: 562ms
     CGroup: /system.slice/qgsd.service
             └─3420 /usr/bin/qgs

Apr 15 04:01:58 sdp qgsd[3420]: Added a new connection, now [1]
Apr 15 04:01:58 sdp qgsd[3420]: handle_read: status [system:0]
Apr 15 04:01:58 sdp qgsd[3420]: handle_read:[system:0Received 1024 bytes.]
Apr 15 04:01:58 sdp qgsd[3420]: process raw request [1024] bytes!.
Apr 15 04:01:58 sdp qgsd[3420]: unpack message successfully in thread [7e7650e89740]
Apr 15 04:01:58 sdp qgsd[3420]: tee_att_get_quote_size return Success
Apr 15 04:01:58 sdp qgsd[3420]: tee_att_get_quote return Success
Apr 15 04:01:58 sdp qgsd[3420]: About to write response in thread [7e764f2006c0]
Apr 15 04:01:58 sdp qgsd[3420]: About to shutdown and close socket
Apr 15 04:01:58 sdp qgsd[3420]: erased a connection, now [0]
```

### PCCS service status

```
● pccs.service - Provisioning Certificate Caching Service (PCCS)
     Loaded: loaded (/usr/lib/systemd/system/pccs.service; enabled; preset: enabled)
     Active: active (running) since Thu 2025-04-10 04:32:25 PDT; 1 week 6 days ago
       Docs: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md
   Main PID: 3312 (node)
      Tasks: 15 (limit: 629145)
     Memory: 122.8M (peak: 125.1M)
        CPU: 22.109s
     CGroup: /system.slice/pccs.service
             └─3312 /usr/bin/node /opt/intel/sgx-dcap-pccs/pccs_server.js

Apr 24 01:00:03 sdp node[3312]: 2025-04-24 01:00:03.726 [info]: Request-ID is : 808bcbd16bc3477b89aade4437801d53
Apr 24 01:00:04 sdp node[3312]: 2025-04-24 01:00:04.102 [info]: Request-ID is : ffe4d20ac83b41fe832f9233125bc661
Apr 24 01:00:04 sdp node[3312]: 2025-04-24 01:00:04.473 [info]: Request-ID is : 77b2fe1532cb450181771d9172bc1e5a
Apr 24 01:00:04 sdp node[3312]: 2025-04-24 01:00:04.834 [info]: Request-ID is : 29d794a7d26e4ff996f83d836aa29734
Apr 24 01:00:05 sdp node[3312]: 2025-04-24 01:00:05.214 [info]: Request-ID is : cac6b860782c4542938b0b585c9a1ad2
Apr 24 01:00:05 sdp node[3312]: 2025-04-24 01:00:05.603 [info]: Request-ID is : 881bef53cd714be6a5bf5d4cb8550813
Apr 24 01:00:06 sdp node[3312]: 2025-04-24 01:00:06.018 [info]: Request-ID is : 83aa972a4f7d46fd9b6d55a03e0edc9f
Apr 24 01:00:06 sdp node[3312]: 2025-04-24 01:00:06.380 [info]: Request-ID is : 572e78f289c440cb8173bdfb6f12e9bd
Apr 24 01:00:06 sdp node[3312]: 2025-04-24 01:00:06.739 [info]: Request-ID is : c556ac4d9b1b41bab50884b69fb1d57e
Apr 24 01:00:06 sdp node[3312]: 2025-04-24 01:00:06.902 [info]: Scheduled cache refresh is completed successfully.
```

### MPA registration logs (last 30 lines)

```
[08-04-2025 10:20:29] INFO: SGX Registration Agent version: 1.21.100.3
[08-04-2025 10:20:29] INFO: Starts Registration Agent Flow.
[08-04-2025 10:20:29] INFO: SGX MP Server configuration flag indicates that Registration Server won't save encrypted platform keys.
[08-04-2025 10:20:29] INFO: Platform registration request (PLATFORM_MANIFEST) won't be send to Registration Server.
[08-04-2025 10:20:29] INFO: Please use management tool or PCKCertIDRetrievalTool to read PLATFORM_MANIFEST.
[08-04-2025 10:20:29] INFO: Finished Registration Agent Flow.
[08-04-2025 10:25:02] INFO: SGX Registration Agent version: 1.21.100.3
[08-04-2025 10:25:02] INFO: Starts Registration Agent Flow.
[08-04-2025 10:25:02] INFO: SGX MP Server configuration flag indicates that Registration Server won't save encrypted platform keys.
[08-04-2025 10:25:02] INFO: Platform registration request (PLATFORM_MANIFEST) won't be send to Registration Server.
[08-04-2025 10:25:02] INFO: Please use management tool or PCKCertIDRetrievalTool to read PLATFORM_MANIFEST.
[08-04-2025 10:25:02] INFO: Finished Registration Agent Flow.
[08-04-2025 10:44:54] INFO: SGX Registration Agent version: 1.21.100.3
[08-04-2025 10:44:54] INFO: Starts Registration Agent Flow.
[08-04-2025 10:44:55] INFO: Registration Flow - PLATFORM_ESTABLISHMENT or TCB_RECOVERY passed successfully.
[08-04-2025 10:44:55] INFO: Finished Registration Agent Flow.
[10-04-2025 04:32:26] INFO: SGX Registration Agent version: 1.21.100.3
[10-04-2025 04:32:26] INFO: Starts Registration Agent Flow.
[10-04-2025 04:32:26] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[10-04-2025 04:32:26] INFO: Finished Registration Agent Flow.
```

### PR DESCRIPTION
**Pull request by hector-cao**
Ubuntu make the kernels (vmlinuz) readable ONLY for root user this makes libguestfs fails when it is run as normal user For more details, see the LP bug on that topic:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/759725 To work-around this issue, we allow normal users to read the kernel files

Fixes #352 

JIRA #PEK-1760

### CODE REVIEW

File: guest-tools/image/create-td-uki.sh [hunk 1]
```diff
@@ -47,6 +47,14 @@ cleanup
 
 set -e
 
+# Ubuntu make the kernels (vmlinuz) readable ONLY for root user
+# this makes libguestfs fails when it is run as normal user
+# For more details, see the LP bug on that topic:
+# https://bugs.launchpad.net/ubuntu/+source/linux/+bug/759725
+# To work-around this issue, we allow normal users to read the kernel
+# files
+sudo chmod 0644 /boot/vmlinuz-*
```
Comment (mckees) [inline guest-tools/image/create-td-uki.sh:56]: There seems to be some discussion in the LP bug about it being a change for security's sake. I know there's a lot of... disagreement on that point, but if it's being kept in place despite a lot of pushback, I assume our security folks have a decent reason for the default. 

Since this is a security-focused project, have you looked for other ways to grant read access for libguestfs or maybe a group that libguestfs is a member of to avoid granting read access to everyone on the system?

Comment (hector-cao) [reply guest-tools/image/create-td-uki.sh:56]: In the LP issue thread discussions, it has been proposed that we can enable read access to every one for components that need it, the push back is on enabling it by default.

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/759725/comments/3

Comment (mckees) [reply guest-tools/image/create-td-uki.sh:56]: Yes, but the language there is recommending that this is an option for admins who want to "relax this restriction". I'm just wondering if you fall into that category or if TDX is the type of product that might actually benefit from leaving the restriction in place

Comment (hector-cao) [reply guest-tools/image/create-td-uki.sh:56]: This operation is only for building images for the direct boot, it can be done outside of the TDX host and does not affect TDX runtime security
